### ISSUE TITLE
Standardize face numbering and orientation

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/CubedSphere.jl#7]
It would be good to standardize (a) the numbering of the faces of the sphere, and (b) the orientation of each face.

Currently ClimateMachine uses Ronchi, Iacono, Paolucci (1996) numbering:
<img width="277" alt="Screen Shot 2021-03-15 at 2 18 00 PM" src="https://user-images.githubusercontent.com/1692009/111222616-50fa3f00-8599-11eb-9c69-6f15bf2b75a7.png">
This has the downside that the faces aren't sequentially connected (i.e. face V isn't connected to VI) which makes it harder to use space-filling curves.

[Dennis (2003)](http://www.cs.umanitoba.ca/pub/IPDPS03/DATA/W17_WMPP_11.PDF) proposes the following:
<img width="334" alt="Screen Shot 2021-03-15 at 2 22 03 PM" src="https://user-images.githubusercontent.com/1692009/111223076-e72e6500-8599-11eb-9e4b-c2ff35c02899.png">
which lets you use a Hilbert curve.

Are there others? @jm-c @christophernhill ?

**Comment by ali-ramadhan** [comment]
I don't think that CubedSphere.jl specifies any numbering yet. I guess we want flexible topology/numbering so maybe we should be standardizing the default?

For Oceananigans.jl we're starting with the topology from this figure of the MITgcm manual https://mitgcm.readthedocs.io/en/latest/phys_pkgs/exch2.html?highlight=cube%20sphere#fig-48tile

We're also trying to keep things flexible enough so we can change the topology/numbering in the future.

My understanding is the MITgcm topology helps keep the halo exchanges at the edges thing neater/tidier with a finite volume algorithm but @christophernhill and @jm-c should have more to say (I could also be wrong).

**Comment by simonbyrne** [comment]
Is there a convention for how these map to physical coordinates? i.e. which face contains the north pole, etc.?

**Comment by ali-ramadhan** [comment]
I'm not sure... I think MITgcm uses that particular convention so that faces 2 and 5 (?) contain the poles. But for Oceananigans.jl I allowed for the faces to be rotated arbitrarily so you could e.g. move the corners onto land.

I think MITgcm also allows for the faces to be rotated around but not sure if it's a commonly used feature?

**Comment by simonbyrne** [comment]
@jakebolewski pointed out that the s2 library from google is based on a cubed sphere:
https://s2geometry.io/devguide/s2cell_hierarchy

**Comment by christophernhill** [comment]
ooh - zero based 😄

**Comment by simonbyrne** [comment]
ClimaCore has settled on the same numbering as MITgcm: https://github.com/CliMA/ClimaCore.jl/blob/ad2e0e00584a0e9a117d465b81dd8cd17d8cb596/src/Meshes/cubedsphere.jl
