### ISSUE TITLE
Rename package to CubedSpheres.jl?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/CubedSphere.jl#9]
Didn't think we would want a `CubedSphere` type since there are multiple kinds, e.g. `ConformalCubedSphere`, `GnomonicCubedSphere`, etc. but if CubedSpheres.jl is a better name, then it's probably best to rename sooner rather than later.

**Comment by glwagner** [comment]
Do it!

**Comment by navidcy** [comment]
I'm deliberating on this since now the package is used by ClimaCore. Should we rename?

cc @simonbyrne

**Comment by charleskawczynski** [comment]
I'm in favor to rip off the band-aid, so long there's nothing immediately needed in upstream packages

**Comment by glwagner** [comment]
Do it.

**Comment by navidcy** [comment]
Given all the complications that this would imply I am closing this and we'll live with the CubedSphere :)

**Comment by glwagner** [comment]
bummer

**Comment by navidcy** [comment]
You can think of the package name as the generic, ethereal cubed sphere with various many flavors... :)

**Comment by glwagner** [comment]
The name has always bothered me. Speaks to the importance of getting it right the first time.

**Comment by navidcy** [comment]
`CubedSphere` bothered you but `CubedSpheres` does not?

**Comment by navidcy** [comment]
Because if you have a suggestion that is far-distant from `CubeSphere` we'll consider it. :)

**Comment by navidcy** [comment]
Apparently

> Package name similar to 1 existing package.
> Similar to CubedSphere. Damerau-Levenshtein distance 1 is at or below cutoff of 2. Damerau-Levenshtein distance 1 between lowercased names is at or below cutoff of 1. Normalized visual distance 2.19 is at or below cutoff of 2.50.

somehow there is a way to quantify how distance between names. :)

**Comment by glwagner** [comment]
Seems important for spell checking
